jdbcDriverClass: com.mysql.cj.jdbc.Driver
jdbcDbUrl: jdbc:mysql://localhost:3306/property_manager
jdbcUserName: root
jdbcUserPassword: YOUR_PASSWORD
poolSize: 10
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
